import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import type { Page } from '@playwright/test';
import { test, expect, route, sendChat, nativeDialog, root } from '../fixtures';

const gitExe = process.env.HERMES_E2E_GIT || 'C:\\Users\\admin\\Desktop\\Dev\\Git\\cmd\\git.exe';
function git(folder: string, ...args: string[]) {
  return execFileSync(gitExe, ['-C', folder, ...args], { encoding: 'utf8' }).trim();
}

async function projectChat(app: Page, prefix: string) {
  const name = `${prefix}-${Date.now()}`;
  const folder = path.join(root, 'workspace', name);
  mkdirSync(path.join(folder, 'nested'), { recursive: true });
  writeFileSync(path.join(folder, 'readme.md'), '# Native E2E\r\noriginal content\r\n');
  writeFileSync(path.join(folder, 'nested', 'note.txt'), 'nested file evidence');
  git(folder, 'init', '-b', 'main');
  git(folder, 'config', 'user.name', 'Hermes E2E');
  git(folder, 'config', 'user.email', 'e2e@localhost');
  git(folder, 'add', '.');
  git(folder, 'commit', '-m', 'test: 初始化本地端到端项目');
  await route(app, '/projects');
  await app.getByRole('button', { name: '添加项目', exact: true }).first().click();
  await nativeDialog('选择工作区', folder);
  await app.getByPlaceholder('按名称或路径搜索…').fill(name);
  await app.getByRole('row').filter({ hasText: name }).click();
  const projectRoute = new URL(app.url()).hash.slice(1);
  await app.getByRole('button', { name: '新对话', exact: true }).click();
  await expect(app.getByRole('button', { name: new RegExp('不指定默认工作区：') })).toHaveAttribute('aria-label', `不指定默认工作区：${folder}`);
  const result = await sendChat(app, `当前工作区是 ${folder}。请调用读取文件工具读取 readme.md，回复其中的英文内容，不要修改文件。`, 'original content');
  const rail = app.getByRole('complementary', { name: '预览面板', exact: true });
  if (!await rail.isVisible()) await app.getByRole('button', { name: '预览面板', exact: true }).click();
  await expect(rail).toBeVisible();
  return { folder, name, projectRoute, rail, result };
}

test('PROJ-002 项目真实对话、文件树、Git 差异暂存还原与本地提交', async ({ app }, testInfo) => {
  const { folder, projectRoute, rail, result } = await projectChat(app, 'git-project');
  await rail.getByRole('tab', { name: '文件', exact: true }).click();
  await rail.getByRole('button', { name: 'nested', exact: true }).click();
  await rail.getByRole('button', { name: 'note.txt', exact: true }).click();
  await expect(rail).toContainText('nested file evidence');
  writeFileSync(path.join(folder, 'readme.md'), '# Native E2E\r\nreview change\r\n');
  await rail.getByRole('tab', { name: '改动', exact: true }).click();
  await rail.locator('[role="button"][title="readme.md"]').click();
  await expect(rail.locator('pre')).toContainText('+review change');
  await expect(rail.locator('pre')).toContainText('-original content');
  const toggle = rail.getByRole('button', { name: /切换为.*视图/ });
  await toggle.click();
  await toggle.click();
  await rail.getByRole('button', { name: '暂存', exact: true }).last().click();
  await expect.poll(() => git(folder, 'diff', '--cached', '--name-only')).toBe('readme.md');
  await rail.getByRole('button', { name: '取消暂存', exact: true }).last().click();
  await expect.poll(() => git(folder, 'diff', '--cached', '--name-only')).toBe('');
  await rail.getByRole('button', { name: '还原全部改动', exact: true }).click();
  await app.getByRole('dialog', { name: '还原全部改动' }).getByRole('button', { name: '取消', exact: true }).click();
  expect(readFileSync(path.join(folder, 'readme.md'), 'utf8')).toContain('review change');
  await rail.getByRole('button', { name: '还原全部改动', exact: true }).click();
  await app.getByRole('dialog', { name: '还原全部改动' }).getByRole('button', { name: '还原全部', exact: true }).click();
  await expect.poll(() => git(folder, 'status', '--porcelain')).toBe('');
  writeFileSync(path.join(folder, 'readme.md'), '# Native E2E\r\ncommitted from Desktop\r\n');
  await rail.getByRole('button', { name: '刷新改动列表', exact: true }).click();
  await rail.getByRole('button', { name: '暂存全部', exact: true }).click();
  await rail.getByRole('combobox', { name: '提交方式', exact: true }).selectOption('commit');
  await rail.getByPlaceholder('提交说明（⌘/Ctrl+Enter 提交）').fill('test: 验证桌面端本地提交');
  await rail.getByRole('button', { name: '提交', exact: true }).click();
  await expect.poll(() => git(folder, 'log', '-1', '--format=%s')).toBe('test: 验证桌面端本地提交');
  expect(git(folder, 'remote')).toBe('');
  await route(app, projectRoute);
  await expect(app.getByRole('table')).toContainText('deepseek-v4-flash');
  await testInfo.attach('project-evidence', { body: JSON.stringify({ folder, commit: git(folder, 'rev-parse', 'HEAD'), session: result.evidence.session }, null, 2), contentType: 'application/json' });
});

test('CHAT-009 文件预览编辑、未保存取消、磁盘冲突、分屏及日志', async ({ app }, testInfo) => {
  const { folder, rail, result } = await projectChat(app, 'file-preview');
  await rail.getByRole('tab', { name: '文件', exact: true }).click();
  await rail.getByRole('button', { name: 'readme.md', exact: true }).click();
  await expect(rail).toContainText('original content');
  await rail.getByRole('button', { name: '编辑', exact: true }).click();
  const editor = rail.getByRole('textbox', { name: '文件内容编辑器', exact: true });
  await editor.fill('# Native E2E\nUI saved content\n');
  await editor.press('Control+s');
  await expect.poll(() => readFileSync(path.join(folder, 'readme.md'), 'utf8')).toBe('# Native E2E\r\nUI saved content\r\n');
  await editor.fill('unsaved draft');
  await rail.getByRole('tab', { name: '改动', exact: true }).click();
  await app.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click();
  await expect(editor).toHaveValue('unsaved draft');
  await editor.press('Escape');
  await app.getByRole('dialog').getByRole('button', { name: '放弃修改', exact: true }).click();
  await expect(editor).toHaveCount(0);
  await rail.getByRole('button', { name: '编辑', exact: true }).click();
  await editor.fill('draft before outside write');
  writeFileSync(path.join(folder, 'readme.md'), 'outside content\r\n');
  await rail.getByRole('button', { name: '保存', exact: true }).click();
  await expect(rail.getByText('文件已在磁盘上发生变化', { exact: true })).toBeVisible();
  expect(readFileSync(path.join(folder, 'readme.md'), 'utf8')).toBe('outside content\r\n');
  await rail.getByRole('button', { name: '放弃并重新加载', exact: true }).click();
  await expect(rail).toContainText('outside content');
  await rail.getByRole('button', { name: '编辑', exact: true }).click();
  await editor.fill('explicit overwrite\n');
  writeFileSync(path.join(folder, 'readme.md'), 'second outside write\r\n');
  await rail.getByRole('button', { name: '保存', exact: true }).click();
  await rail.getByRole('button', { name: '覆盖保存', exact: true }).click();
  await expect.poll(() => readFileSync(path.join(folder, 'readme.md'), 'utf8')).toBe('explicit overwrite\r\n');
  await rail.getByRole('button', { name: '取消', exact: true }).click();
  const before = (await rail.boundingBox())!;
  const grip = (await rail.getByRole('separator', { name: '调整预览面板宽度' }).boundingBox())!;
  await app.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2);
  await app.mouse.down();
  await app.mouse.move(grip.x - 100, grip.y + grip.height / 2, { steps: 5 });
  await app.mouse.up();
  expect((await rail.boundingBox())!.width).toBeGreaterThan(before.width);
  await expect(rail.getByRole('button', { name: '产物', exact: true })).toBeDisabled();
  await rail.getByRole('tab', { name: '日志', exact: true }).click();
  await rail.getByRole('textbox', { name: '搜索日志' }).fill('impossible-log-marker');
  await expect(rail).toContainText('没有匹配的日志。');
  await rail.getByRole('textbox', { name: '搜索日志' }).fill('');
  await expect(rail.getByRole('log')).not.toBeEmpty();
  await rail.getByRole('button', { name: '关闭预览面板' }).click();
  await expect(rail).toHaveCount(0);
  await testInfo.attach('file-editor-session', { body: JSON.stringify(result.evidence.session, null, 2), contentType: 'application/json' });
});
