import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { test, expect, route, bridge, root, sessionEvidence } from '../fixtures';

test('RUNTIME-003 更新提醒、真实进度与取消、任务等待、界面生效与失败恢复', async ({ app }, testInfo) => {
  test.setTimeout(420_000);
  const fixture = path.join(root, 'update-fixture');
  const modeFile = path.join(fixture, 'mode.json');
  const currentFile = path.join(root, 'runtime', 'ui', 'current.json');
  const before = await bridge<any>(app, 'getRuntimeInfo');
  const state = () => bridge<any>(app, 'softwareUpdateSnapshot');
  const mode = (ui: string | null, delayMs = 0) => writeFileSync(modeFile, JSON.stringify({ ...JSON.parse(readFileSync(modeFile, 'utf8')), ui, delayMs }));
  const check = async () => {
    await route(app, '/updates?advanced=1');
    await app.getByRole('button', { name: '检查界面更新', exact: true }).click();
    await expect.poll(async () => (await state()).phase).not.toBe('checking');
  };
  const download = async () => {
    await app.getByRole('button', { name: /^(下载更新|重新下载)$/ }).click();
    await expect.poll(async () => (await state()).phase, { timeout: 120_000 }).toMatch(/^(ready|waiting)$/);
  };
  const rollback = async () => {
    await route(app, '/updates?advanced=1');
    await app.getByRole('button', { name: '回退界面', exact: true }).click();
    const loaded = app.waitForEvent('load');
    await app.getByRole('dialog', { name: '回退界面版本', exact: true }).getByRole('button', { name: '回退', exact: true }).click();
    await loaded;
    await app.waitForFunction(() => (window as any).__HERMES_RUNTIME__?.backendReady);
  };
  expect(existsSync(currentFile)).toBe(false);
  try {
    mode('ui-1.json', 25);
    await check();
    expect((await state()).currentVersion).toBe('0.9.0');
    await route(app, '/');
    const notice = app.getByRole('dialog', { name: 'Hermes 有更新可用', exact: true });
    await expect(notice).toBeVisible();
    await testInfo.attach('automatic-update-modal', { body: await app.screenshot(), contentType: 'image/png' });
    await notice.getByRole('button', { name: '稍后提醒', exact: true }).click();
    await app.getByRole('link', { name: '软件更新：有可用更新', exact: true }).click();
    await expect(app).toHaveURL(/#\/updates$/);
    await expect(app.getByLabel('runtimeManifestUrl（可选，完整覆盖）')).toBeHidden();
    await route(app, '/');
    await expect(notice).toBeHidden();
    await route(app, '/updates');
    await app.getByRole('button', { name: '下载更新', exact: true }).click();
    await expect(app.getByRole('progressbar', { name: '更新下载进度' })).toBeVisible();
    await expect.poll(async () => (await state()).downloadedBytes).toBeGreaterThan(0);
    await testInfo.attach('real-download-progress', { body: JSON.stringify(await state()), contentType: 'application/json' });
    await app.getByRole('button', { name: '取消下载', exact: true }).click();
    await expect.poll(async () => (await state()).phase).toBe('available');
    expect(existsSync(currentFile)).toBe(false);
    mode('ui-1.json');
    await download();
    await app.reload();
    await app.waitForFunction(() => (window as any).__HERMES_RUNTIME__?.backendReady);
    expect((await state()).phase).toBe('ready');
    mode(null);
    await app.getByRole('button', { name: '刷新界面并应用', exact: true }).click();
    await expect.poll(async () => (await state()).error?.code).toBe('candidate_changed');
    expect(existsSync(currentFile)).toBe(false);
    mode('ui-bad-hash.json');
    await check();
    await app.getByRole('button', { name: '下载更新', exact: true }).click();
    await expect.poll(async () => (await state()).error?.code, { timeout: 120_000 }).toBe('verification_failed');
    mode('ui-1.json');
    await check();
    await download();
    // A real model/tool run proves the native activity registry protects work.
    const marker = `update-wait-${Date.now()}`;
    const started = path.join(root, 'workspace', marker + '-start.txt');
    const finished = path.join(root, 'workspace', marker + '-done.txt');
    await route(app, '/');
    const readyNotice = app.getByRole('dialog', { name: '更新已准备好', exact: true });
    if (await readyNotice.isVisible()) await readyNotice.getByRole('button', { name: '稍后提醒', exact: true }).click();
    const command = `powershell -NoProfile -Command "Set-Content -LiteralPath '${started.replaceAll('\\', '/')}' -Value START; Start-Sleep -Seconds 25; Set-Content -LiteralPath '${finished.replaceAll('\\', '/')}' -Value DONE"`;
    await app.getByRole('textbox', { name: '输入消息', exact: true }).fill(`使用 terminal 同步执行下面命令，timeout=60，不要放到后台。成功后仅回复 UPDATE-TASK-DONE。命令：${command}`);
    await app.getByRole('button', { name: '发送消息', exact: true }).click();
    await expect(app).toHaveURL(/#\/tasks\//);
    const session = decodeURIComponent(app.url().split('#/tasks/')[1].split('?')[0]);
    await expect.poll(() => existsSync(started), { timeout: 90_000 }).toBe(true);
    await route(app, '/updates');
    await expect(app.getByRole('heading', { name: '等待任务结束', exact: true })).toBeVisible();
    expect((await state()).activities.length).toBeGreaterThan(0);
    expect(existsSync(currentFile)).toBe(false);
    await expect.poll(() => existsSync(finished), { timeout: 90_000 }).toBe(true);
    await expect.poll(async () => (await state()).phase, { timeout: 90_000 }).toBe('ready');
    const evidence = sessionEvidence(session);
    expect(evidence.session.billing_provider).toBe('deepseek');
    expect(evidence.session.model).toBe('deepseek-v4-flash');
    expect(evidence.session.output_tokens).toBeGreaterThan(0);
    await testInfo.attach('real-work-protected', { body: JSON.stringify(evidence), contentType: 'application/json' });
    const applied = app.waitForEvent('load');
    await app.getByRole('button', { name: '刷新界面并应用', exact: true }).click();
    await applied;
    await expect(app.locator('meta[name="hermes-native-e2e-ui"]')).toHaveAttribute('content', '1');
    await expect.poll(async () => (await state()).phase).toBe('completed');
    expect((await bridge<any>(app, 'getRuntimeInfo')).process.pid).toBe(before.process.pid);
    expect((await state()).currentVersion).toBe('0.9.0');
    await expect(app).toHaveURL(/#\/updates$/);
    mode('ui-broken-launch.json');
    await check();
    await download();
    await app.getByRole('button', { name: '刷新界面并应用', exact: true }).click();
    await expect(app.getByText('Update recovery test', { exact: true })).toBeVisible();
    await expect(app.locator('meta[name="hermes-native-e2e-ui"]')).toHaveAttribute('content', '1', { timeout: 70_000 });
    await expect.poll(async () => (await state()).phase).toBe('error');
    expect(JSON.parse(readFileSync(currentFile, 'utf8')).uiVersion).toBe('0.9.1-e2e.1');
    await testInfo.attach('failed-ui-restored', { body: await app.screenshot(), contentType: 'image/png' });
    await rollback();
    expect(existsSync(currentFile)).toBe(false);
    expect((await bridge<any>(app, 'getRuntimeInfo')).process.pid).toBe(before.process.pid);
  } finally {
    mode('ui-1.json');
    if (!app.isClosed() && existsSync(currentFile)) await rollback();
  }
});
