// AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.
// Active brand: hermesagent. Run `pnpm brand:sync` with BRAND=<id> to regenerate.

export interface BrandConfig {
  id: string;
  appName: string;
  appNameEn: string;
  productName: string;
  identifier: string;
  dataDirName: string;
  providerKey: string;
  serviceUrl: string;
  registerUrl: string;
  rechargeUrl: string;
  copyright: string;
  publisher: string;
  homepage: string;
  shortDescription: string;
  longDescription: string;
  tagline: string;
  edition: string;
  updateManifestUrl: string;
  updateDownloadUrl: string;
  accountDefaultModels: readonly string[];
  accountModelDescriptions?: Readonly<Record<string, string>>;
}

export const BRAND: BrandConfig = {
  "id": "hermesagent",
  "appName": "HermesAgent",
  "appNameEn": "HermesAgent",
  "productName": "HermesAgent Desktop",
  "identifier": "cn.org.hermesagent.desktop",
  "dataDirName": ".HermesAgent",
  "providerKey": "HermesAgent",
  "serviceUrl": "https://api.huanxing.ai/",
  "registerUrl": "https://api.huanxing.ai/sign-up",
  "rechargeUrl": "https://api.huanxing.ai/wallet",
  "copyright": "Copyright © 2026 HermesAgent",
  "publisher": "HermesAgent",
  "homepage": "https://api.huanxing.ai",
  "shortDescription": "HermesAgent AI Assistant Desktop",
  "longDescription": "Desktop app for HermesAgent AI Assistant.",
  "tagline": "AI Assistant",
  "edition": "桌面版",
  "updateManifestUrl": "https://ai.fengchiyun.com/downloads/HermesAgent/latest.json",
  "updateDownloadUrl": "https://api.huanxing.ai/hermes-client",
  "accountDefaultModels": [
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "gpt-5.6-sol",
    "kimi-k3"
  ],
  "accountModelDescriptions": {
    "deepseek-v4-flash": "响应快、成本低，适合日常问答、轻量代码修改和批量文本处理。",
    "deepseek-v4-pro": "更强的推理和代码能力，适合复杂开发、长链路分析和高质量写作。",
    "gpt-5.6-sol": "通用能力强，适合综合任务、工具调用、多轮规划和复杂问题拆解。",
    "kimi-k3": "长文本阅读和中文理解表现稳定，适合资料分析、总结和知识密集型任务。",
    "claude-opus-4-8": "复杂推理、代码架构和长上下文任务表现突出，只支持 Claude Code 中使用。"
  }
} as const;

export default BRAND;
