import type { SessionRow, MessageRow, SqlParam, TitleSource } from "./types";

export type { SqlParam };

/**
 * Pluggable SQL adapter used by SessionStore.
 *
 * In production this forwards to the Rust `state_db_*` Tauri commands. In unit
 * tests the `MemorySqlAdapter` implements the same narrow surface without a
 * real SQLite database or Rust runtime.
 */
export interface SqlAdapter {
  query(sql: string, params?: SqlParam[], options?: { readonly?: boolean }): Promise<Record<string, unknown>[]>;
  exec(sql: string, params?: SqlParam[]): Promise<number>;
}

interface HermesDesktopStateDb {
  query: (input: { sql: string; params?: SqlParam[]; readonly?: boolean }) => Promise<Record<string, unknown>[]>;
  exec: (input: { sql: string; params?: SqlParam[] }) => Promise<number>;
  ftsSearch?: (input: { sql: string; params?: SqlParam[] }) => Promise<Record<string, unknown>[]>;
}

function getWindowHermesDesktop(): { stateDb?: HermesDesktopStateDb } {
  if (typeof window === "undefined") return {};
  return (window as unknown as { hermesDesktop?: { stateDb?: HermesDesktopStateDb } }).hermesDesktop ?? {};
}

/**
 * Build a SQL adapter that invokes the Rust Tauri `state_db_query` /
 * `state_db_exec` commands via `window.hermesDesktop.stateDb`.
 */
export function createTauriSqlAdapter(): SqlAdapter {
  return {
    async query(sql, params, options) {
      const bridge = getWindowHermesDesktop().stateDb;
      if (!bridge) {
        throw new Error("hermesDesktop.stateDb is not available");
      }
      return bridge.query({ sql, params, readonly: options?.readonly ?? true });
    },
    async exec(sql, params) {
      const bridge = getWindowHermesDesktop().stateDb;
      if (!bridge) {
        throw new Error("hermesDesktop.stateDb is not available");
      }
      return bridge.exec({ sql, params });
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// In-memory SQL adapter for unit tests. This is intentionally not a full SQL
// engine — it pattern-matches the exact subset of SQL issued by SessionStore.
// ─────────────────────────────────────────────────────────────────────────────

function normalizeSql(sql: string): string {
  return sql
    .replace(/\s+/g, " ")
    .replace(/\s*,\s*/g, ", ")
    .trim();
}

export interface MemorySqlAdapterState {
  sessions: Map<string, SessionRow>;
  messages: MessageRow[];
  stateMeta: Map<string, string>;
  nextMessageId: number;
}

export function createEmptyMemorySqlAdapterState(): MemorySqlAdapterState {
  return {
    sessions: new Map(),
    messages: [],
    stateMeta: new Map(),
    nextMessageId: 1,
  };
}

/**
 * In-memory SQL adapter implementing the schema v25 subset used by lifecycle
 * commands. It is not a generic SQLite replacement — it recognizes the specific
 * queries generated by `SessionStore`.
 */
export class MemorySqlAdapter implements SqlAdapter {
  private state: MemorySqlAdapterState;

  constructor(state?: MemorySqlAdapterState) {
    this.state = state ?? createEmptyMemorySqlAdapterState();
  }

  getState(): MemorySqlAdapterState {
    return this.state;
  }

  async query(sql: string, params: SqlParam[] = []): Promise<Record<string, unknown>[]> {
    const normalized = normalizeSql(sql);
    const result = this.tryQuery(normalized, params);
    if (result === undefined) {
      throw new Error(`MemorySqlAdapter: unsupported query: ${normalized}`);
    }
    return result;
  }

  async exec(sql: string, params: SqlParam[] = []): Promise<number> {
    const normalized = normalizeSql(sql);
    const result = this.tryExec(normalized, params);
    if (result === undefined) {
      throw new Error(`MemorySqlAdapter: unsupported exec: ${normalized}`);
    }
    return result;
  }

  private tryQuery(sql: string, params: SqlParam[]): Record<string, unknown>[] | undefined {
    // SELECT * FROM sessions WHERE id = ?
    {
      const m = /SELECT \* FROM sessions WHERE id = \?/i.exec(sql);
      if (m) {
        const id = String(params[0] ?? "");
        const row = this.state.sessions.get(id);
        return row ? [rowToRecord(row)] : [];
      }
    }

    // SELECT id FROM sessions WHERE id = ?
    {
      const m = /SELECT (\w+) FROM sessions WHERE id = \?/i.exec(sql);
      if (m) {
        const col = m[1];
        const id = String(params[0] ?? "");
        const row = this.state.sessions.get(id);
        if (!row) return [];
        return [{ [col]: (row as unknown as Record<string, unknown>)[col] }];
      }
    }

    // SELECT id FROM sessions WHERE id = ?
    {
      const m = /SELECT id FROM sessions WHERE id = \?/i.exec(sql);
      if (m) {
        const id = String(params[0] ?? "");
        const row = this.state.sessions.get(id);
        return row ? [{ id: row.id }] : [];
      }
    }

    // SELECT COUNT(*) as count FROM sessions [WHERE ...]
    {
      const m = /SELECT COUNT\(\*\) as count FROM sessions(.*)/i.exec(sql);
      if (m) {
        const where = m[1] ?? "";
        let count = 0;
        for (const row of this.state.sessions.values()) {
          if (this.matchesSessionWhere(row, where, params)) count++;
        }
        return [{ count }];
      }
    }

    // SELECT * FROM sessions ... ORDER BY ... LIMIT ? OFFSET ?
    {
      const m = /SELECT \* FROM sessions(.*) ORDER BY (.*?) LIMIT \? OFFSET \?/i.exec(sql);
      if (m) {
        const where = m[1] ?? "";
        const orderBy = m[2] ?? "";
        const limit = Number(params[params.length - 2] ?? 0);
        const offset = Number(params[params.length - 1] ?? 0);
        let rows = Array.from(this.state.sessions.values()).filter((row) =>
          this.matchesSessionWhere(row, where, params.slice(0, params.length - 2)),
        );
        rows = this.orderSessions(rows, orderBy);
        return rows.slice(offset, offset + limit).map(rowToRecord);
      }
    }

    // SELECT id FROM sessions WHERE id LIKE ? || '%' ORDER BY started_at DESC
    {
      const m = /SELECT id FROM sessions WHERE id LIKE \? \|\| '%' ORDER BY started_at DESC/i.exec(sql);
      if (m) {
        const prefix = String(params[0] ?? "");
        const rows = Array.from(this.state.sessions.values())
          .filter((row) => row.id.startsWith(prefix))
          .sort((a, b) => b.started_at - a.started_at);
        return rows.map((row) => ({ id: row.id }));
      }
    }

    // SELECT * FROM messages WHERE session_id = ? AND active = 1 ORDER BY id ASC
    {
      const m = /SELECT \* FROM messages WHERE session_id = \? AND active = (\d) ORDER BY id ASC/i.exec(sql);
      if (m) {
        const sessionId = String(params[0] ?? "");
        const active = Number(m[1]);
        return this.state.messages
          .filter((msg) => msg.session_id === sessionId && msg.active === active)
          .sort((a, b) => a.id - b.id)
          .map(messageToRecord);
      }
    }

    // SELECT * FROM messages WHERE session_id = ? ORDER BY id ASC
    {
      const m = /SELECT \* FROM messages WHERE session_id = \? ORDER BY id ASC/i.exec(sql);
      if (m) {
        const sessionId = String(params[0] ?? "");
        return this.state.messages
          .filter((msg) => msg.session_id === sessionId)
          .sort((a, b) => a.id - b.id)
          .map(messageToRecord);
      }
    }

    // SELECT id, content, role FROM messages WHERE session_id = ? AND role = 'user' AND active = 1 ORDER BY id DESC LIMIT 1
    {
      const m =
        /SELECT id, content, role FROM messages WHERE session_id = \? AND role = 'user' AND active = 1 ORDER BY id DESC LIMIT 1/i.exec(
          sql,
        );
      if (m) {
        const sessionId = String(params[0] ?? "");
        const matches = this.state.messages
          .filter((msg) => msg.session_id === sessionId && msg.role === "user" && msg.active === 1)
          .sort((a, b) => b.id - a.id);
        const top = matches[0];
        return top ? [{ id: top.id, content: top.content, role: top.role }] : [];
      }
    }

    // SELECT id, content[, role] FROM messages WHERE session_id = ? AND id >= ? AND role = 'user' AND active = 1 ORDER BY id ASC LIMIT 1
    {
      const m =
        /SELECT id, content(?:, role)? FROM messages WHERE session_id = \? AND id >= \? AND role = 'user' AND active = 1 ORDER BY id ASC LIMIT 1/i.exec(
          sql,
        );
      if (m) {
        const sessionId = String(params[0] ?? "");
        const minId = Number(params[1] ?? 0);
        const matches = this.state.messages
          .filter(
            (msg) =>
              msg.session_id === sessionId && msg.id >= minId && msg.role === "user" && msg.active === 1,
          )
          .sort((a, b) => a.id - b.id);
        const top = matches[0];
        return top ? [{ id: top.id, content: top.content, role: top.role }] : [];
      }
    }

    // SELECT COUNT(*) as count FROM messages WHERE session_id = ? AND active = 1|0
    {
      const m = /SELECT COUNT\(\*\) as count FROM messages WHERE session_id = \? AND active = (\d)/i.exec(sql);
      if (m) {
        const sessionId = String(params[0] ?? "");
        const active = Number(m[1]);
        const count = this.state.messages.filter((msg) => msg.session_id === sessionId && msg.active === active).length;
        return [{ count }];
      }
    }

    // SELECT COUNT(*) as count FROM messages WHERE session_id = ? AND id >= ? AND active = 0
    {
      const m = /SELECT COUNT\(\*\) as count FROM messages WHERE session_id = \? AND id >= \? AND active = (\d)/i.exec(sql);
      if (m) {
        const sessionId = String(params[0] ?? "");
        const minId = Number(params[1] ?? 0);
        const active = Number(m[1]);
        const count = this.state.messages.filter(
          (msg) => msg.session_id === sessionId && msg.id >= minId && msg.active === active,
        ).length;
        return [{ count }];
      }
    }

    // SELECT COUNT(*) as count FROM messages WHERE session_id = ? AND id >= ? AND id <= ? AND active = ?
    {
      const m =
        /SELECT COUNT\(\*\) as count FROM messages WHERE session_id = \? AND id >= \? AND id <= \? AND active = \?/i.exec(
          sql,
        );
      if (m) {
        const sessionId = String(params[0] ?? "");
        const minId = Number(params[1] ?? 0);
        const maxId = Number(params[2] ?? 0);
        const active = Number(params[3] ?? 0);
        const count = this.state.messages.filter(
          (msg) =>
            msg.session_id === sessionId && msg.id >= minId && msg.id <= maxId && msg.active === active,
        ).length;
        return [{ count }];
      }
    }

    // SELECT MAX(timestamp) as max_ts FROM messages WHERE session_id = ? AND active = 1
    {
      const m = /SELECT MAX\(timestamp\) as max_ts FROM messages WHERE session_id = \? AND active = 1/i.exec(sql);
      if (m) {
        const sessionId = String(params[0] ?? "");
        const max = this.state.messages
          .filter((msg) => msg.session_id === sessionId && msg.active === 1)
          .reduce((acc, msg) => Math.max(acc, msg.timestamp), 0);
        return [{ max_ts: max || null }];
      }
    }

    // SELECT metadata_json FROM sessions WHERE id = ?
    {
      const m = /SELECT metadata_json FROM sessions WHERE id = \?/i.exec(sql);
      if (m) {
        const id = String(params[0] ?? "");
        const row = this.state.sessions.get(id);
        return row ? [{ metadata_json: row.metadata_json }] : [];
      }
    }

    // SELECT id, parent_session_id, end_reason, source FROM sessions WHERE id IN (...)
    {
      const m = /SELECT id, parent_session_id, end_reason, source FROM sessions WHERE id IN \((.*)\)/i.exec(sql);
      if (m) {
        const placeholders = m[1].split(",").map((s) => s.trim());
        const ids = params.slice(0, placeholders.length).map(String);
        const result: Record<string, unknown>[] = [];
        for (const id of ids) {
          const row = this.state.sessions.get(id);
          if (row) {
            result.push({
              id: row.id,
              parent_session_id: row.parent_session_id,
              end_reason: row.end_reason,
              source: row.source,
            });
          }
        }
        return result;
      }
    }

    // SELECT id, started_at, end_reason, source FROM sessions WHERE parent_session_id = ?
    {
      const m = /SELECT id, started_at, end_reason, source FROM sessions WHERE parent_session_id = \?/i.exec(sql);
      if (m) {
        const parentId = String(params[0] ?? "");
        return Array.from(this.state.sessions.values())
          .filter((row) => row.parent_session_id === parentId)
          .map((row) => ({
            id: row.id,
            started_at: row.started_at,
            end_reason: row.end_reason,
            source: row.source,
          }));
      }
    }

    // SELECT * FROM messages WHERE content LIKE ? AND active = 1 ORDER BY id DESC LIMIT ?
    {
      const m = /SELECT \* FROM messages WHERE content LIKE \? AND active = 1 ORDER BY id DESC LIMIT \?/i.exec(sql);
      if (m) {
        const pattern = String(params[0] ?? "").replace(/%/g, "");
        const limit = Number(params[1] ?? 50);
        return this.state.messages
          .filter(
            (msg) =>
              msg.active === 1 &&
              msg.content &&
              msg.content.toLowerCase().includes(pattern.toLowerCase()),
          )
          .sort((a, b) => b.id - a.id)
          .slice(0, limit)
          .map(messageToRecord);
      }
    }

    return undefined;
  }

  private matchesSessionWhere(row: SessionRow, where: string, params: SqlParam[]): boolean {
    const normalized = where.trim();
    if (!normalized || normalized.toLowerCase() === "") return true;

    // WHERE archived = ?
    {
      const m = /WHERE archived = \?/i.exec(normalized);
      if (m) {
        return row.archived === Number(params[0] ?? 0);
      }
    }

    // WHERE parent_session_id = ?
    {
      const m = /WHERE parent_session_id = \?/i.exec(normalized);
      if (m) {
        const expected = params[0];
        if (expected === null) return row.parent_session_id === null;
        return row.parent_session_id === String(expected);
      }
    }

    return true;
  }

  private orderSessions(rows: SessionRow[], orderBy: string): SessionRow[] {
    const key = orderBy.trim().toLowerCase().replace(/\s+(asc|desc)$/i, "");
    const desc = /desc\s*$/i.test(orderBy);
    const sorted = [...rows].sort((a, b) => {
      const av = ((a as unknown as Record<string, number | null>)[key] ?? 0);
      const bv = ((b as unknown as Record<string, number | null>)[key] ?? 0);
      if (av === null && bv === null) return 0;
      if (av === null) return 1;
      if (bv === null) return -1;
      return av < bv ? -1 : av > bv ? 1 : 0;
    });
    return desc ? sorted.reverse() : sorted;
  }

  private tryExec(sql: string, params: SqlParam[]): number | undefined {
    // INSERT INTO sessions (...) VALUES (...)
    {
      const m = /INSERT INTO sessions \(([^)]+)\) VALUES \(([^)]+)\)/i.exec(sql);
      if (m) {
        const columns = m[1].split(",").map((s) => s.trim());
        const row: Record<string, unknown> = {};
        for (let i = 0; i < columns.length; i++) {
          row[columns[i]] = params[i];
        }
        this.state.sessions.set(String(row.id), recordToSessionRow(row));
        return 1;
      }
    }

    // INSERT INTO messages (...) VALUES (...)
    {
      const m = /INSERT INTO messages \(([^)]+)\) VALUES \(([^)]+)\)/i.exec(sql);
      if (m) {
        const columns = m[1].split(",").map((s) => s.trim());
        const row: Record<string, unknown> = { id: this.state.nextMessageId };
        this.state.nextMessageId += 1;
        for (let i = 0; i < columns.length; i++) {
          row[columns[i]] = params[i];
        }
        this.state.messages.push(recordToMessageRow(row));
        return 1;
      }
    }

    // UPDATE sessions SET ... WHERE id = ?
    {
      const m = /UPDATE sessions SET (.*?) WHERE id = \?/i.exec(sql);
      if (m) {
        const id = String(params[params.length - 1] ?? "");
        const row = this.state.sessions.get(id);
        if (!row) return 0;
        const setClause = m[1];
        const pairs = setClause.split(",").map((s) => s.trim());
        const updates: Record<string, SqlParam> = {};
        let paramIndex = 0;
        for (const pair of pairs) {
          const eq = pair.indexOf("=");
          if (eq === -1) continue;
          const col = pair.slice(0, eq).trim();
          updates[col] = params[paramIndex];
          paramIndex++;
        }
        applyUpdates(row, updates);
        return 1;
      }
    }

    // UPDATE messages SET active = ? WHERE session_id = ? AND id >= ?
    {
      const m = /UPDATE messages SET active = \? WHERE session_id = \? AND id >= \?/i.exec(sql);
      if (m) {
        const active = Number(params[0]);
        const sessionId = String(params[1] ?? "");
        const minId = Number(params[2] ?? 0);
        let count = 0;
        for (const msg of this.state.messages) {
          if (msg.session_id === sessionId && msg.id >= minId) {
            msg.active = active;
            count++;
          }
        }
        return count;
      }
    }

    // UPDATE messages SET active = ? WHERE session_id = ? AND id = ?
    {
      const m = /UPDATE messages SET active = \? WHERE session_id = \? AND id = \?/i.exec(sql);
      if (m) {
        const active = Number(params[0]);
        const sessionId = String(params[1] ?? "");
        const messageId = Number(params[2] ?? 0);
        const msg = this.state.messages.find((m) => m.session_id === sessionId && m.id === messageId);
        if (msg) {
          msg.active = active;
          return 1;
        }
        return 0;
      }
    }

    // UPDATE messages SET active = ? WHERE session_id = ?
    {
      const m = /UPDATE messages SET active = \? WHERE session_id = \?/i.exec(sql);
      if (m) {
        const active = Number(params[0]);
        const sessionId = String(params[1] ?? "");
        let count = 0;
        for (const msg of this.state.messages) {
          if (msg.session_id === sessionId) {
            msg.active = active;
            count++;
          }
        }
        return count;
      }
    }

    // UPDATE messages SET active = ?, compacted = ? WHERE session_id = ? AND id >= ? AND id <= ?
    {
      const m =
        /UPDATE messages SET active = \?, compacted = \? WHERE session_id = \? AND id >= \? AND id <= \?/i.exec(
          sql,
        );
      if (m) {
        const active = Number(params[0]);
        const compacted = Number(params[1]);
        const sessionId = String(params[2] ?? "");
        const minId = Number(params[3] ?? 0);
        const maxId = Number(params[4] ?? 0);
        let count = 0;
        for (const msg of this.state.messages) {
          if (msg.session_id === sessionId && msg.id >= minId && msg.id <= maxId) {
            msg.active = active;
            msg.compacted = compacted;
            count++;
          }
        }
        return count;
      }
    }

    // DELETE FROM sessions WHERE id = ?
    {
      const m = /DELETE FROM sessions WHERE id = \?/i.exec(sql);
      if (m) {
        const id = String(params[0] ?? "");
        const existed = this.state.sessions.delete(id);
        if (existed) {
          this.state.messages = this.state.messages.filter((msg) => msg.session_id !== id);
        }
        return existed ? 1 : 0;
      }
    }

    return undefined;
  }
}

function rowToRecord(row: SessionRow): Record<string, unknown> {
  return { ...(row as unknown as Record<string, unknown>) };
}

function messageToRecord(row: MessageRow): Record<string, unknown> {
  return { ...(row as unknown as Record<string, unknown>) };
}

function recordToSessionRow(record: Record<string, unknown>): SessionRow {
  return {
    id: String(record.id ?? ""),
    source: record.source === null ? null : String(record.source ?? ""),
    user_id: record.user_id === null ? null : String(record.user_id ?? ""),
    session_key: record.session_key === null ? null : String(record.session_key ?? ""),
    chat_id: record.chat_id === null ? null : String(record.chat_id ?? ""),
    chat_type: record.chat_type === null ? null : String(record.chat_type ?? ""),
    thread_id: record.thread_id === null ? null : String(record.thread_id ?? ""),
    parent_session_id: record.parent_session_id === null ? null : String(record.parent_session_id ?? ""),
    model_config: record.model_config === null ? null : String(record.model_config ?? ""),
    title: record.title === null ? null : String(record.title ?? ""),
    title_source: (record.title_source as TitleSource | null) ?? null,
    started_at: Number(record.started_at ?? 0),
    ended_at: record.ended_at === null ? null : Number(record.ended_at),
    end_reason: record.end_reason === null ? null : String(record.end_reason ?? ""),
    cwd: record.cwd === null ? null : String(record.cwd ?? ""),
    git_branch: record.git_branch === null ? null : String(record.git_branch ?? ""),
    handoff_state: record.handoff_state === null ? null : String(record.handoff_state ?? ""),
    archived: Number(record.archived ?? 0),
    pinned: Number(record.pinned ?? 0),
    rewind_count: Number(record.rewind_count ?? 0),
    last_activity_at: record.last_activity_at === null ? null : Number(record.last_activity_at),
    model: record.model === null ? null : String(record.model ?? ""),
    message_count: Number(record.message_count ?? 0),
    input_tokens: Number(record.input_tokens ?? 0),
    output_tokens: Number(record.output_tokens ?? 0),
    metadata_json:
      record.metadata_json === null || record.metadata_json === undefined
        ? null
        : String(record.metadata_json),
  } as SessionRow;
}

function recordToMessageRow(record: Record<string, unknown>): MessageRow {
  return {
    id: Number(record.id ?? 0),
    session_id: String(record.session_id ?? ""),
    role: record.role === null ? null : String(record.role ?? ""),
    content: record.content === null ? null : String(record.content ?? ""),
    tool_calls: record.tool_calls === null ? null : String(record.tool_calls ?? ""),
    tool_call_id: record.tool_call_id === null ? null : String(record.tool_call_id ?? ""),
    tool_name: record.tool_name === null ? null : String(record.tool_name ?? ""),
    effect_disposition: record.effect_disposition === null ? null : String(record.effect_disposition ?? ""),
    timestamp: Number(record.timestamp ?? 0),
    token_count: record.token_count === null ? null : Number(record.token_count),
    finish_reason: record.finish_reason === null ? null : String(record.finish_reason ?? ""),
    reasoning: record.reasoning === null ? null : String(record.reasoning ?? ""),
    reasoning_content: record.reasoning_content === null ? null : String(record.reasoning_content ?? ""),
    reasoning_details: record.reasoning_details === null ? null : String(record.reasoning_details ?? ""),
    codex_reasoning_items: record.codex_reasoning_items === null ? null : String(record.codex_reasoning_items ?? ""),
    platform_message_id: record.platform_message_id === null ? null : String(record.platform_message_id ?? ""),
    observed: Number(record.observed ?? 0),
    active: Number(record.active ?? 1),
    compacted: Number(record.compacted ?? 0),
    api_content: record.api_content === null ? null : String(record.api_content ?? ""),
    display_kind: record.display_kind === null ? null : String(record.display_kind ?? ""),
    display_metadata: record.display_metadata === null ? null : String(record.display_metadata ?? ""),
  } as MessageRow;
}

function applyUpdates(row: SessionRow, updates: Record<string, SqlParam>): void {
  const mutable = row as unknown as Record<string, SqlParam>;
  for (const [key, value] of Object.entries(updates)) {
    if (key in row) {
      mutable[key] = value;
    }
  }
}
