// AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.
// Active brand: hermesagent. Run `pnpm brand:sync` with BRAND=<id> to regenerate.

pub const BRAND_ID: &str = "hermesagent";
pub const BRAND_APP_NAME: &str = "HermesAgent";
pub const BRAND_APP_NAME_EN: &str = "HermesAgent";
pub const BRAND_PRODUCT_NAME: &str = "HermesAgent Desktop";
pub const BRAND_PROVIDER_KEY: &str = "HermesAgent";
pub const BRAND_SERVICE_URL: &str = "https://api.huanxing.ai/";
pub const BRAND_REGISTER_URL: &str = "https://api.huanxing.ai/sign-up";
pub const BRAND_RECHARGE_URL: &str = "https://api.huanxing.ai/wallet";
pub const BRAND_DATA_DIR_NAME: &str = ".HermesAgent";
pub const BRAND_WINDOW_TITLE: &str = "HermesAgent 桌面版";
pub const BRAND_HOMEPAGE: &str = "https://api.huanxing.ai";
pub const BRAND_UPDATE_MANIFEST_URL: &str =
    "https://huanxing.tos-cn-beijing.volces.com/package/hermesagent/hermesagent/latest.json";
pub const BRAND_UPDATE_DOWNLOAD_URL: &str = "https://api.huanxing.ai/hermes-client";
