// AUTO-GENERATED by scripts/sync-brand.mjs - do not edit by hand.
// Active brand: huanxingcomhermes. Run `pnpm brand:sync` with BRAND=<id> to regenerate.

pub const BRAND_ID: &str = "huanxingcomhermes";
pub const BRAND_APP_NAME: &str = "HermesAgent";
pub const BRAND_APP_NAME_EN: &str = "HermesAgent";
pub const BRAND_PRODUCT_NAME: &str = "HuanxingHermes Desktop";
pub const BRAND_PROVIDER_KEY: &str = "huanxinghermes";
pub const BRAND_SERVICE_URL: &str = "https://huanxingapi.com/";
pub const BRAND_TEAM_SERVICE_URL: &str = "https://team.huanxingapi.com";
pub const BRAND_REGISTER_URL: &str = "https://huanxingapi.com/sign-up";
pub const BRAND_RECHARGE_URL: &str = "https://huanxingapi.com/wallet";
pub const BRAND_DATA_DIR_NAME: &str = ".huanxinghermes";
pub const BRAND_WINDOW_TITLE: &str = "HermesAgent 桌面版";
pub const BRAND_HOMEPAGE: &str = "https://api.huanxing.ai";
pub const BRAND_UPDATE_MANIFEST_URL: &str =
    "https://huanxing.tos-cn-beijing.volces.com/package/hermesagent/huanxinghermes/latest.json";
pub const BRAND_UPDATE_DOWNLOAD_URL: &str = "https://huanxingapi.com/hermes-client";
