/**
 * Approval gate types for the in-process agent.
 *
 * The gate sits in front of every tool call. Policies decide whether the call
 * should proceed (`approve`), be blocked (`deny`), or be held for user review
 * (`ask`). The `ApprovalGate` owns pending requests and emits lifecycle events.
 */

/** Persistent / process-level approval mode. */
export type ApprovalMode = "manual" | "smart" | "yolo" | "off";

/** UI presentation mode for a single approval request. */
export type ApprovalRequestMode = "yolo" | "suggest" | "confirm";

/** How dangerous an operation is considered to be. */
export type DangerLevel = "none" | "low" | "medium" | "high" | "critical";

/** User resolution scope for a single approval decision. */
export type ApprovalScope = "once" | "session" | "always" | "deny";

/** Gate decision for a tool call. */
export type ApprovalDecision = "approve" | "deny" | "ask";

export interface ApprovalPolicyResult {
  decision: ApprovalDecision;
  /** Human-readable reason (for logging / UI). */
  reason?: string;
}

export interface ApprovalRequest {
  /** Stable id generated by the gate. */
  id: string;
  sessionId: string;
  turnId?: string;
  toolName: string;
  /** Stringified tool arguments for display / matching. */
  toolArgs?: string;
  /** Optional resolved toolset for policy matching. */
  toolset?: string;
  /** Human-readable description of the operation. */
  description?: string;
  dangerLevel: DangerLevel;
  /** How the UI should present the request. */
  mode?: ApprovalRequestMode;
}

export interface ApprovalResponse {
  requestId: string;
  decision: ApprovalDecision;
  scope?: ApprovalScope;
  /** Free-text feedback attached to a deny or conditional approve. */
  feedback?: string;
}

export interface ApprovalPolicy {
  readonly name: string;
  evaluate(request: ApprovalRequest): ApprovalPolicyResult | undefined;
}

/** Normalized result returned by `ApprovalGate.request`. */
export interface ApprovalResult {
  requestId: string;
  decision: ApprovalDecision;
  /** Present only when the gate asked and the user approved. */
  response?: ApprovalResponse;
}
